<a href="https://colab.research.google.com/github/Lekuro/Intership_ML/blob/lesson_07_numpy/lesson_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1050]:
import numpy as np

In [1051]:
arr_int=np.random.randint(-100,100, size=(4,5))
arr_int

array([[-30, -82,  59, -93,  56],
       [ 11,  12,  99, -71,   4],
       [ 74, -88,  77, -39,  78],
       [-36,  11,  77, -36, -11]])

In [1052]:
arr_n=np.random.randn(4,5)

In [1053]:
arr=np.arange(-9,11)
arr

array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10])

# Новий розділ

In [1054]:
arr45=arr.reshape(4,5)
arr45

array([[-9, -8, -7, -6, -5],
       [-4, -3, -2, -1,  0],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [1055]:
arr45.shape

(4, 5)

In [1056]:
arr_copy=np.copy(arr45[:3,:4])
arr_copy

array([[-9, -8, -7, -6],
       [-4, -3, -2, -1],
       [ 1,  2,  3,  4]])

In [1057]:
arr_copy[2:]=0
arr_copy[:,3:]=0
arr_copy

array([[-9, -8, -7,  0],
       [-4, -3, -2,  0],
       [ 0,  0,  0,  0]])

In [1058]:
arr_copy[:2,:3]

array([[-9, -8, -7],
       [-4, -3, -2]])

In [1059]:
arr45

array([[-9, -8, -7, -6, -5],
       [-4, -3, -2, -1,  0],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [1060]:
arr451=arr45[..., np.newaxis]
arr451

array([[[-9],
        [-8],
        [-7],
        [-6],
        [-5]],

       [[-4],
        [-3],
        [-2],
        [-1],
        [ 0]],

       [[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [1061]:
arr451.shape

(4, 5, 1)

In [1062]:
class UnaryMethods:
  def __init__(self,arr2d,slice_list=[],copy_number=1):
    slice_data=slice_list if slice_list else arr2d.shape
    # self.arr2d=np.copy(arr2d[:slice_data[0],:slice_data[1]])
    self.arr2d=arr2d[:slice_data[0],:slice_data[1]]
    self.copy=copy_number
    self.arr3d=None

  def repeat(self):
    if self.arr3d and self.arr3d.shape==self.copy:
      return self.arr3d
    # self.arr3d=self.arr2d[...,np.newaxis]
    # self.arr3d= np.repeat(self.arr3d,self.copy, axis=2)
    self.arr3d=self.arr2d[np.newaxis]
    self.arr3d= np.repeat(self.arr3d,self.copy, axis=0)
    return self.arr3d

  def get_abs(self):
    return np.abs(self.arr2d)

  def get_sqrt(self):
    return np.sqrt(self.arr2d)

  def get_square(self):
    return np.square(self.arr2d)

  def get_exp(self):
    return np.exp(self.arr2d)

  def get_log(self):
    return np.log(self.arr2d)

  def get_log10(self):
    return np.log10(self.arr2d)

  def get_log2(self):
    return np.log2(self.arr2d)

  def get_log1p(self):
    return np.log1p(self.arr2d)

  def get_sign(self):
    return np.sign(self.arr2d)

  def get_ceil(self):
    return np.ceil(self.arr2d)

  def get_floor(self):
    return np.floor(self.arr2d)

  def get_rint(self):
    return np.rint(self.arr2d)

  def get_modf(self):
    return np.modf(self.arr2d)

  def get_isnan(self):
    return np.isnan(self.arr2d)

  def get_isfinite(self):
    return np.isfinite(self.arr2d)

  def get_isinf(self):
    return np.isinf(self.arr2d)

  def get_cos(self):
    return np.cos(self.arr2d)

  def get_cosh(self):
    return np.cosh(self.arr2d)

  def get_sin(self):
    return np.sin(self.arr2d)

  def get_sinh(self):
    return np.sinh(self.arr2d)

  def get_tan(self):
    return np.tan(self.arr2d)

  def get_tanh(self):
    return np.tanh(self.arr2d)

  def get_arccos(self):
    return np.arccos(self.arr2d)

  def get_arccosh(self):
    return np.arccosh(self.arr2d)

  def get_arcsin(self):
    return np.arcsin(self.arr2d)

  def get_arcsinh(self):
    return np.arcsinh(self.arr2d)

  def get_arctan(self):
    return np.arctan(self.arr2d)

  def get_arctanh(self):
    return np.arctanh(self.arr2d)

  def get_logical_not(self):
    return np.logical_not(self.arr2d)

In [1063]:
um=UnaryMethods(arr_n,(3,4),2)
um.arr2d

array([[ 0.56487299,  0.18783984,  0.81395215, -1.58892316],
       [-0.71792716,  0.94701942,  0.93298239, -0.68061531],
       [-1.336518  , -1.35308865, -0.67347778, -0.5863274 ]])

In [1064]:
um.repeat()

array([[[ 0.56487299,  0.18783984,  0.81395215, -1.58892316],
        [-0.71792716,  0.94701942,  0.93298239, -0.68061531],
        [-1.336518  , -1.35308865, -0.67347778, -0.5863274 ]],

       [[ 0.56487299,  0.18783984,  0.81395215, -1.58892316],
        [-0.71792716,  0.94701942,  0.93298239, -0.68061531],
        [-1.336518  , -1.35308865, -0.67347778, -0.5863274 ]]])

In [1065]:
um.arr3d.shape

(2, 3, 4)

In [1066]:
um.get_abs()

array([[0.56487299, 0.18783984, 0.81395215, 1.58892316],
       [0.71792716, 0.94701942, 0.93298239, 0.68061531],
       [1.336518  , 1.35308865, 0.67347778, 0.5863274 ]])

In [1067]:
um.get_square()

array([[0.3190815 , 0.0352838 , 0.66251811, 2.5246768 ],
       [0.51541941, 0.89684578, 0.87045614, 0.46323721],
       [1.78628035, 1.8308489 , 0.45357231, 0.34377982]])

In [1068]:
um.get_sqrt()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:22: RuntimeWarning: invalid value encountered in sqrt


array([[0.75158033, 0.43340493, 0.90219297,        nan],
       [       nan, 0.97314923, 0.96591014,        nan],
       [       nan,        nan,        nan,        nan]])

In [1069]:
um.get_exp()

array([[1.75922434, 1.20664024, 2.25680964, 0.20414533],
       [0.48776226, 2.57801422, 2.54207936, 0.50630536],
       [0.26275901, 0.25844079, 0.50993206, 0.55636685]])

In [1070]:
um.get_log()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in log


array([[-0.57115436, -1.67216562, -0.2058537 ,         nan],
       [        nan, -0.05443568, -0.06936895,         nan],
       [        nan,         nan,         nan,         nan]])

In [1071]:
um.get_log10()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:34: RuntimeWarning: invalid value encountered in log10


array([[-0.24804919, -0.7262123 , -0.08940112,         nan],
       [        nan, -0.02364112, -0.03012655,         nan],
       [        nan,         nan,         nan,         nan]])

In [1072]:
um.get_log2()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:37: RuntimeWarning: invalid value encountered in log2


array([[-0.82400157, -2.41242505, -0.29698411,         nan],
       [        nan, -0.07853408, -0.10007824,         nan],
       [        nan,         nan,         nan,         nan]])

In [1073]:
um.get_log1p()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:40: RuntimeWarning: invalid value encountered in log1p


array([[ 0.44780467,  0.17213639,  0.59550797,         nan],
       [-1.26558995,  0.6662997 ,  0.65906409, -1.14135899],
       [        nan,         nan, -1.11925726, -0.88268045]])

In [1074]:
um.get_sign()

array([[ 1.,  1.,  1., -1.],
       [-1.,  1.,  1., -1.],
       [-1., -1., -1., -1.]])

In [1075]:
um.get_ceil()

array([[ 1.,  1.,  1., -1.],
       [-0.,  1.,  1., -0.],
       [-1., -1., -0., -0.]])

In [1076]:
um.get_floor()

array([[ 0.,  0.,  0., -2.],
       [-1.,  0.,  0., -1.],
       [-2., -2., -1., -1.]])

In [1077]:
um.get_rint()

array([[ 1.,  0.,  1., -2.],
       [-1.,  1.,  1., -1.],
       [-1., -1., -1., -1.]])

In [1078]:
um.get_modf()

(array([[ 0.56487299,  0.18783984,  0.81395215, -0.58892316],
        [-0.71792716,  0.94701942,  0.93298239, -0.68061531],
        [-0.336518  , -0.35308865, -0.67347778, -0.5863274 ]]),
 array([[ 0.,  0.,  0., -1.],
        [-0.,  0.,  0., -0.],
        [-1., -1., -0., -0.]]))

In [1079]:
um.get_isnan()

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [1080]:
um.get_isfinite()

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [1081]:
um.get_isinf()

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [1082]:
um.get_cos()

array([[ 0.84465659,  0.98240991,  0.68663056, -0.01812584],
       [ 0.75317091,  0.58410495,  0.59544058,  0.77718567],
       [ 0.23214109,  0.21599198,  0.78165728,  0.83297836]])

In [1083]:
um.get_cosh()

array([[1.16382834, 1.01769384, 1.34995652, 2.55130826],
       [1.26897069, 1.48295484, 1.46772906, 1.24069901],
       [2.03426386, 2.0638995 , 1.23548881, 1.17687105]])

In [1084]:
um.get_sin()

array([[ 0.53530854,  0.18673716,  0.72700651, -0.99983571],
       [-0.65782488,  0.81167814,  0.80339935, -0.62927136],
       [-0.97268212, -0.97639514, -0.62370818, -0.55330557]])

In [1085]:
um.get_sinh()

array([[ 0.595396  ,  0.1889464 ,  0.90685313, -2.34716294],
       [-0.78120842,  1.09505938,  1.07435031, -0.73439365],
       [-1.77150485, -1.8054587 , -0.72555674, -0.6205042 ]])

In [1086]:
um.get_tan()

array([[ 0.63375879,  0.1900807 ,  1.05880302, 55.16080398],
       [-0.87340718,  1.3896101 ,  1.34925192, -0.80967957],
       [-4.19004717, -4.52051579, -0.7979305 , -0.66424963]])

In [1087]:
um.get_tanh()

array([[ 0.51158404,  0.18566134,  0.67176469, -0.91998406],
       [-0.6156237 ,  0.7384307 ,  0.73198136, -0.59191927],
       [-0.87083337, -0.87478034, -0.5872629 , -0.5272491 ]])

In [1088]:
um.get_arccos()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:85: RuntimeWarning: invalid value encountered in arccos


array([[0.97051699, 1.38183396, 0.61987315,        nan],
       [2.37161634, 0.32697134, 0.3681843 , 2.31939849],
       [       nan,        nan, 2.30969983, 2.19731403]])

In [1089]:
um.get_arccosh()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:88: RuntimeWarning: invalid value encountered in arccosh


array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]])

In [1090]:
um.get_arcsin()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:91: RuntimeWarning: invalid value encountered in arcsin


array([[ 0.60027933,  0.18896237,  0.95092317,         nan],
       [-0.80082002,  1.24382499,  1.20261202, -0.74860217],
       [        nan,         nan, -0.7389035 , -0.62651771]])

In [1091]:
um.get_arcsinh()

array([[ 0.53847137,  0.1867524 ,  0.74352602, -1.24309796],
       [-0.66729122,  0.84341017,  0.83318239, -0.63671372],
       [-1.10052163, -1.11040954, -0.63080339, -0.55706544]])

In [1092]:
um.get_arctan()

array([[ 0.51419026,  0.18567622,  0.68319064, -1.00906998],
       [-0.62265656,  0.75819376,  0.75074147, -0.59759729],
       [-0.92843995, -0.93434021, -0.59270318, -0.53030545]])

In [1093]:
um.get_arctanh()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:100: RuntimeWarning: invalid value encountered in arctanh


array([[ 0.63996099,  0.19009705,  1.13862968,         nan],
       [-0.90335418,  1.80206477,  1.68093199, -0.83025949],
       [        nan,         nan, -0.81708061, -0.67205099]])

In [1094]:
um.get_logical_not()

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [1095]:
um=UnaryMethods(arr45,copy_number=3)
um.arr2d

array([[-9, -8, -7, -6, -5],
       [-4, -3, -2, -1,  0],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [1096]:
res=um.repeat()
res

array([[[-9, -8, -7, -6, -5],
        [-4, -3, -2, -1,  0],
        [ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[-9, -8, -7, -6, -5],
        [-4, -3, -2, -1,  0],
        [ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[-9, -8, -7, -6, -5],
        [-4, -3, -2, -1,  0],
        [ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [1097]:
res.shape

(3, 4, 5)