<a href="https://colab.research.google.com/github/Lekuro/Intership_ML/blob/lesson_07_numpy/lesson_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [520]:
import numpy as np

In [521]:
arr_int=np.random.randint(-100,100, size=(4,5))
arr_int

array([[-24, -55,  99,  85, -85],
       [ 73, -92,  -6,  30,  19],
       [ 81,  -8, -80,  19, -40],
       [-20,   9,   1,   1,  -3]])

In [522]:
arr_n=np.random.randn(4,5)

In [523]:
arr=np.arange(-9,11)
arr

array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10])

# Новий розділ

In [524]:
arr45=arr.reshape(4,5)
arr45

array([[-9, -8, -7, -6, -5],
       [-4, -3, -2, -1,  0],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [525]:
arr45.shape

(4, 5)

In [526]:
arr_copy=np.copy(arr45[:3,:4])
arr_copy

array([[-9, -8, -7, -6],
       [-4, -3, -2, -1],
       [ 1,  2,  3,  4]])

In [527]:
arr_copy[2:]=0
arr_copy[:,3:]=0
arr_copy

array([[-9, -8, -7,  0],
       [-4, -3, -2,  0],
       [ 0,  0,  0,  0]])

In [528]:
arr_copy[:2,:3]

array([[-9, -8, -7],
       [-4, -3, -2]])

In [529]:
arr45

array([[-9, -8, -7, -6, -5],
       [-4, -3, -2, -1,  0],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [530]:
class UnaryMethods:
  def __init__(self,arr2d,slice_list=[],copy_number=1):
    slice_data=slice_list if slice_list else arr2d.shape
    # self.arr2d=np.copy(arr2d[:slice_data[0],:slice_data[1]])
    self.arr2d=arr2d[:slice_data[0],:slice_data[1]]
    self.copy=copy_number

  def get_abs(self):
    return np.abs(self.arr2d)

  def get_sqrt(self):
    return np.sqrt(self.arr2d)

  def get_square(self):
    return np.square(self.arr2d)

  def get_exp(self):
    return np.exp(self.arr2d)

  def get_log(self):
    return np.log(self.arr2d)

  def get_log10(self):
    return np.log10(self.arr2d)

  def get_log2(self):
    return np.log2(self.arr2d)

  def get_log1p(self):
    return np.log1p(self.arr2d)

  def get_sign(self):
    return np.sign(self.arr2d)

  def get_ceil(self):
    return np.ceil(self.arr2d)

  def get_floor(self):
    return np.floor(self.arr2d)

  def get_rint(self):
    return np.rint(self.arr2d)

  def get_modf(self):
    return np.modf(self.arr2d)

  def get_isnan(self):
    return np.isnan(self.arr2d)

  def get_isfinite(self):
    return np.isfinite(self.arr2d)

  def get_isinf(self):
    return np.isinf(self.arr2d)

  def get_cos(self):
    return np.cos(self.arr2d)

  def get_cosh(self):
    return np.cosh(self.arr2d)

  def get_sin(self):
    return np.sin(self.arr2d)

  def get_sinh(self):
    return np.sinh(self.arr2d)

  def get_tan(self):
    return np.tan(self.arr2d)

  def get_tanh(self):
    return np.tanh(self.arr2d)

  def get_arccos(self):
    return np.arccos(self.arr2d)

  def get_arccosh(self):
    return np.arccosh(self.arr2d)

  def get_arcsin(self):
    return np.arcsin(self.arr2d)

  def get_arcsinh(self):
    return np.arcsinh(self.arr2d)

  def get_arctan(self):
    return np.arctan(self.arr2d)

  def get_arctanh(self):
    return np.arctanh(self.arr2d)

  def get_logical_not(self):
    return np.logical_not(self.arr2d)

In [531]:
um=UnaryMethods(arr_n,(3,4))
um.arr2d

array([[ 2.04614416,  1.62244703, -1.57701317, -0.31201499],
       [-0.5091803 ,  1.50761251,  1.13846883, -0.77590949],
       [-0.16957183, -1.07922811,  0.9765341 , -0.46606446]])

In [532]:
um.get_abs()

array([[2.04614416, 1.62244703, 1.57701317, 0.31201499],
       [0.5091803 , 1.50761251, 1.13846883, 0.77590949],
       [0.16957183, 1.07922811, 0.9765341 , 0.46606446]])

In [533]:
um.get_square()

array([[4.18670594, 2.63233438, 2.48697054, 0.09735335],
       [0.25926457, 2.27289547, 1.29611127, 0.60203554],
       [0.02875461, 1.16473332, 0.95361884, 0.21721608]])

In [534]:
um.get_sqrt()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in sqrt
  if sys.path[0] == '':


array([[1.43043496, 1.27375313,        nan,        nan],
       [       nan, 1.22784873, 1.06699055,        nan],
       [       nan,        nan, 0.9881974 ,        nan]])

In [535]:
um.get_exp()

array([[7.73800703, 5.06547054, 0.20659123, 0.73197056],
       [0.60098801, 4.51593615, 3.12198441, 0.46028496],
       [0.84402612, 0.33985776, 2.65523748, 0.62746684]])

In [536]:
um.get_log()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in log


array([[ 0.71595713,  0.48393552,         nan,         nan],
       [        nan,  0.41052728,  0.12968423,         nan],
       [        nan,         nan, -0.02374561,         nan]])

In [537]:
um.get_log10()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: RuntimeWarning: invalid value encountered in log10


array([[ 0.31093623,  0.21017053,         nan,         nan],
       [        nan,  0.17828973,  0.05632114,         nan],
       [        nan,         nan, -0.01031259,         nan]])

In [538]:
um.get_log2()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:27: RuntimeWarning: invalid value encountered in log2


array([[ 1.0329078 ,  0.69817138,         nan,         nan],
       [        nan,  0.59226567,  0.18709479,         nan],
       [        nan,         nan, -0.03425768,         nan]])

In [539]:
um.get_log1p()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:30: RuntimeWarning: invalid value encountered in log1p


array([[ 1.11387658,  0.96410786,         nan, -0.37398823],
       [-0.71167842,  0.91933111,  0.76009007, -1.49570527],
       [-0.18581385,         nan,  0.68134485, -0.62748015]])

In [540]:
um.get_sign()

array([[ 1.,  1., -1., -1.],
       [-1.,  1.,  1., -1.],
       [-1., -1.,  1., -1.]])

In [541]:
um.get_ceil()

array([[ 3.,  2., -1., -0.],
       [-0.,  2.,  2., -0.],
       [-0., -1.,  1., -0.]])

In [542]:
um.get_floor()

array([[ 2.,  1., -2., -1.],
       [-1.,  1.,  1., -1.],
       [-1., -2.,  0., -1.]])

In [543]:
um.get_rint()

array([[ 2.,  2., -2., -0.],
       [-1.,  2.,  1., -1.],
       [-0., -1.,  1., -0.]])

In [544]:
um.get_modf()

(array([[ 0.04614416,  0.62244703, -0.57701317, -0.31201499],
        [-0.5091803 ,  0.50761251,  0.13846883, -0.77590949],
        [-0.16957183, -0.07922811,  0.9765341 , -0.46606446]]),
 array([[ 2.,  1., -1., -0.],
        [-0.,  1.,  1., -0.],
        [-0., -1.,  0., -0.]]))

In [545]:
um.get_isnan()

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [546]:
um.get_isfinite()

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [547]:
um.get_isinf()

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [548]:
um.get_cos()

array([[-0.45764775, -0.05162775, -0.0062168 ,  0.95171695],
       [ 0.87314437,  0.06314179,  0.41898529,  0.71378435],
       [ 0.98565712,  0.472009  ,  0.55989762,  0.89334373]])

In [549]:
um.get_cosh()

array([[3.93361964, 2.63144279, 2.52353387, 1.04907286],
       [1.13245736, 2.36868709, 1.72114675, 1.31642607],
       [1.01441179, 1.64113261, 1.51592581, 1.11058828]])

In [550]:
um.get_sin()

array([[ 0.88913359,  0.9986664 , -0.99998068, -0.30697696],
       [-0.48746169,  0.99800457,  0.90799302, -0.70036555],
       [-0.16876034, -0.88159373,  0.8285618 , -0.44937398]])

In [551]:
um.get_sinh()

array([[ 3.80438739,  2.43402776, -2.31694264, -0.31710231],
       [-0.53146935,  2.14724906,  1.40083766, -0.8561411 ],
       [-0.17038566, -1.30127486,  1.13931166, -0.48312144]])

In [552]:
um.get_tan()

array([[ -1.94283396, -19.34359894, 160.85127034,  -0.32255069],
       [ -0.55828304,  15.80577002,   2.16712387,  -0.98120048],
       [ -0.17121607,  -1.86774773,   1.47984519,  -0.50302472]])

In [553]:
um.get_tanh()

array([[ 0.96714674,  0.92497841, -0.91813416, -0.3022691 ],
       [-0.46930628,  0.90651444,  0.81389786, -0.65035259],
       [-0.16796499, -0.79291268,  0.75156162, -0.43501399]])

In [554]:
um.get_arccos()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:75: RuntimeWarning: invalid value encountered in arccos


array([[       nan,        nan,        nan, 1.88810949],
       [2.10502844,        nan,        nan, 2.45895186],
       [1.74119152,        nan, 0.21706339, 2.05563367]])

In [555]:
um.get_arccosh()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:78: RuntimeWarning: invalid value encountered in arccosh


array([[1.34319866, 1.06473676,        nan,        nan],
       [       nan, 0.96920161, 0.52035798,        nan],
       [       nan,        nan,        nan,        nan]])

In [556]:
um.get_arcsin()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:81: RuntimeWarning: invalid value encountered in arcsin


array([[        nan,         nan,         nan, -0.31731316],
       [-0.53423211,         nan,         nan, -0.88815553],
       [-0.17039519,         nan,  1.35373294, -0.48483735]])

In [557]:
um.get_arcsinh()

array([[ 1.46408335,  1.26082054, -1.23673705, -0.3071621 ],
       [-0.48940782,  1.19897847,  0.97597799, -0.71374602],
       [-0.16876951, -0.93630172,  0.86468297, -0.45065491]])

In [558]:
um.get_arctan()

array([[ 1.11621005,  1.0184393 , -1.00567272, -0.30244295],
       [-0.47096485,  0.98512783,  0.85005928, -0.65987803],
       [-0.16797399, -0.82348432,  0.77352647, -0.43613253]])

In [559]:
um.get_arctanh()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:90: RuntimeWarning: invalid value encountered in arctanh


array([[        nan,         nan,         nan, -0.32277617],
       [-0.56162254,         nan,         nan, -1.03500897],
       [-0.17122579,         nan,  2.21677582, -0.50503086]])

In [560]:
um.get_logical_not()

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])