<a href="https://colab.research.google.com/github/Lekuro/Intership_ML/blob/lesson_07_numpy/lesson_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1098]:
import numpy as np

In [1099]:
arr_int=np.random.randint(-100,100, size=(4,5))
arr_int

array([[-89,  59, -33, -62,  28],
       [ 89, -72,   5, -78, -26],
       [-87, -20,  19, -32,  57],
       [ 84,  51,  69, -55, -89]])

In [1100]:
arr_n=np.random.randn(4,5)

In [1101]:
arr=np.arange(-9,11)
arr

array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10])

# Новий розділ

In [1102]:
arr45=arr.reshape(4,5)
arr45

array([[-9, -8, -7, -6, -5],
       [-4, -3, -2, -1,  0],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [1103]:
arr45.shape

(4, 5)

In [1104]:
arr_copy=np.copy(arr45[:3,:4])
arr_copy

array([[-9, -8, -7, -6],
       [-4, -3, -2, -1],
       [ 1,  2,  3,  4]])

In [1105]:
arr_copy[2:]=0
arr_copy[:,3:]=0
arr_copy

array([[-9, -8, -7,  0],
       [-4, -3, -2,  0],
       [ 0,  0,  0,  0]])

In [1106]:
arr_copy[:2,:3]

array([[-9, -8, -7],
       [-4, -3, -2]])

In [1107]:
arr45

array([[-9, -8, -7, -6, -5],
       [-4, -3, -2, -1,  0],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [1108]:
arr451=arr45[..., np.newaxis]
arr451

array([[[-9],
        [-8],
        [-7],
        [-6],
        [-5]],

       [[-4],
        [-3],
        [-2],
        [-1],
        [ 0]],

       [[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [1109]:
arr451.shape

(4, 5, 1)

https://note.nkmk.me/en/python-numpy-newaxis/

In [1110]:
class UnaryMethods:
  def __init__(self,arr2d,slice_list=[],copy_number=1):
    slice_data=slice_list if slice_list else arr2d.shape
    # self.arr2d=np.copy(arr2d[:slice_data[0],:slice_data[1]])
    self.arr2d=arr2d[:slice_data[0],:slice_data[1]]
    self.copy=copy_number
    self.arr3d=None

  def repeat(self):
    if self.arr3d and self.arr3d.shape==self.copy:
      return self.arr3d
    # self.arr3d=self.arr2d[...,np.newaxis]
    # self.arr3d= np.repeat(self.arr3d,self.copy, axis=2)
    self.arr3d=self.arr2d[np.newaxis]
    self.arr3d= np.repeat(self.arr3d,self.copy, axis=0)
    return self.arr3d

  def get_abs(self):
    return np.abs(self.arr2d)

  def get_sqrt(self):
    return np.sqrt(self.arr2d)

  def get_square(self):
    return np.square(self.arr2d)

  def get_exp(self):
    return np.exp(self.arr2d)

  def get_log(self):
    return np.log(self.arr2d)

  def get_log10(self):
    return np.log10(self.arr2d)

  def get_log2(self):
    return np.log2(self.arr2d)

  def get_log1p(self):
    return np.log1p(self.arr2d)

  def get_sign(self):
    return np.sign(self.arr2d)

  def get_ceil(self):
    return np.ceil(self.arr2d)

  def get_floor(self):
    return np.floor(self.arr2d)

  def get_rint(self):
    return np.rint(self.arr2d)

  def get_modf(self):
    return np.modf(self.arr2d)

  def get_isnan(self):
    return np.isnan(self.arr2d)

  def get_isfinite(self):
    return np.isfinite(self.arr2d)

  def get_isinf(self):
    return np.isinf(self.arr2d)

  def get_cos(self):
    return np.cos(self.arr2d)

  def get_cosh(self):
    return np.cosh(self.arr2d)

  def get_sin(self):
    return np.sin(self.arr2d)

  def get_sinh(self):
    return np.sinh(self.arr2d)

  def get_tan(self):
    return np.tan(self.arr2d)

  def get_tanh(self):
    return np.tanh(self.arr2d)

  def get_arccos(self):
    return np.arccos(self.arr2d)

  def get_arccosh(self):
    return np.arccosh(self.arr2d)

  def get_arcsin(self):
    return np.arcsin(self.arr2d)

  def get_arcsinh(self):
    return np.arcsinh(self.arr2d)

  def get_arctan(self):
    return np.arctan(self.arr2d)

  def get_arctanh(self):
    return np.arctanh(self.arr2d)

  def get_logical_not(self):
    return np.logical_not(self.arr2d)

In [1111]:
um=UnaryMethods(arr_n,(3,4),2)
um.arr2d

array([[-0.70613987, -1.01219579,  0.64659061,  0.92967054],
       [-2.29703011, -0.42190494, -0.65872426, -0.36755113],
       [-0.03204249,  0.60382343,  0.19912054,  0.64332323]])

In [1112]:
um.repeat()

array([[[-0.70613987, -1.01219579,  0.64659061,  0.92967054],
        [-2.29703011, -0.42190494, -0.65872426, -0.36755113],
        [-0.03204249,  0.60382343,  0.19912054,  0.64332323]],

       [[-0.70613987, -1.01219579,  0.64659061,  0.92967054],
        [-2.29703011, -0.42190494, -0.65872426, -0.36755113],
        [-0.03204249,  0.60382343,  0.19912054,  0.64332323]]])

In [1113]:
um.arr3d.shape

(2, 3, 4)

In [1114]:
um.get_abs()

array([[0.70613987, 1.01219579, 0.64659061, 0.92967054],
       [2.29703011, 0.42190494, 0.65872426, 0.36755113],
       [0.03204249, 0.60382343, 0.19912054, 0.64332323]])

In [1115]:
um.get_square()

array([[4.98633511e-01, 1.02454031e+00, 4.18079422e-01, 8.64287318e-01],
       [5.27634734e+00, 1.78003777e-01, 4.33917650e-01, 1.35093833e-01],
       [1.02672096e-03, 3.64602737e-01, 3.96489911e-02, 4.13864781e-01]])

In [1116]:
um.get_sqrt()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:22: RuntimeWarning: invalid value encountered in sqrt


array([[       nan,        nan, 0.80410858, 0.96419425],
       [       nan,        nan,        nan,        nan],
       [       nan, 0.77706076, 0.44622925, 0.80207433]])

In [1117]:
um.get_exp()

array([[0.49354568, 0.36342011, 1.90902113, 2.5336743 ],
       [0.10055704, 0.65579638, 0.51751112, 0.69242792],
       [0.96846543, 1.82909888, 1.22032906, 1.90279381]])

In [1118]:
um.get_log()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:31: RuntimeWarning: invalid value encountered in log


array([[        nan,         nan, -0.43604193, -0.07292501],
       [        nan,         nan,         nan,         nan],
       [        nan, -0.50447346, -1.61384489, -0.44110799]])

In [1119]:
um.get_log10()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:34: RuntimeWarning: invalid value encountered in log10


array([[        nan,         nan, -0.1893706 , -0.03167093],
       [        nan,         nan,         nan,         nan],
       [        nan, -0.21909004, -0.70088393, -0.19157077]])

In [1120]:
um.get_log2()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:37: RuntimeWarning: invalid value encountered in log2


array([[        nan,         nan, -0.62907553, -0.10520855],
       [        nan,         nan,         nan,         nan],
       [        nan, -0.72780135, -2.32828602, -0.63638431]])

In [1121]:
um.get_log1p()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:40: RuntimeWarning: invalid value encountered in log1p


array([[-1.22465136,         nan,  0.49870686,  0.65734929],
       [        nan, -0.54801696, -1.0750645 , -0.4581559 ],
       [-0.03256708,  0.47239042,  0.18158841,  0.49672055]])

In [1122]:
um.get_sign()

array([[-1., -1.,  1.,  1.],
       [-1., -1., -1., -1.],
       [-1.,  1.,  1.,  1.]])

In [1123]:
um.get_ceil()

array([[-0., -1.,  1.,  1.],
       [-2., -0., -0., -0.],
       [-0.,  1.,  1.,  1.]])

In [1124]:
um.get_floor()

array([[-1., -2.,  0.,  0.],
       [-3., -1., -1., -1.],
       [-1.,  0.,  0.,  0.]])

In [1125]:
um.get_rint()

array([[-1., -1.,  1.,  1.],
       [-2., -0., -1., -0.],
       [-0.,  1.,  0.,  1.]])

In [1126]:
um.get_modf()

(array([[-0.70613987, -0.01219579,  0.64659061,  0.92967054],
        [-0.29703011, -0.42190494, -0.65872426, -0.36755113],
        [-0.03204249,  0.60382343,  0.19912054,  0.64332323]]),
 array([[-0., -1.,  0.,  0.],
        [-2., -0., -0., -0.],
        [-0.,  0.,  0.,  0.]]))

In [1127]:
um.get_isnan()

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [1128]:
um.get_isfinite()

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [1129]:
um.get_isinf()

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [1130]:
um.get_cos()

array([[ 0.76087239,  0.52999998,  0.79814248,  0.59809805],
       [-0.66405843,  0.91231053,  0.79077377,  0.9332101 ],
       [ 0.99948668,  0.82317072,  0.98024092,  0.80010671]])

In [1131]:
um.get_cosh()

array([[1.2598503 , 1.55752825, 1.2164249 , 1.46417901],
       [5.02258063, 1.09032997, 1.22491837, 1.06831078],
       [1.0005134 , 1.18790809, 1.01989008, 1.21416841]])

In [1132]:
um.get_sin()

array([[-0.64890154, -0.84799765,  0.60246874,  0.80142294],
       [-0.74768068, -0.40949909, -0.61210853, -0.3593312 ],
       [-0.032037  ,  0.56779395,  0.19780733,  0.59985769]])

In [1133]:
um.get_sinh()

array([[-0.76630462, -1.19410814,  0.69259623,  1.06949529],
       [-4.92202358, -0.43453359, -0.70740725, -0.37588286],
       [-0.03204797,  0.64119079,  0.20043898,  0.6886254 ]])

In [1134]:
um.get_tan()

array([[-0.85283887, -1.59999564,  0.75483858,  1.33995243],
       [ 1.12592606, -0.44885933, -0.77406276, -0.38504856],
       [-0.03205346,  0.68976452,  0.2017946 ,  0.7497221 ]])

In [1135]:
um.get_tanh()

array([[-0.60825054, -0.76666869,  0.56937032,  0.73044026],
       [-0.97997901, -0.39853403, -0.57751379, -0.35184786],
       [-0.03203153,  0.53976465,  0.19652998,  0.56715805]])

In [1136]:
um.get_arccos()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:85: RuntimeWarning: invalid value encountered in arccos


array([[2.354828  ,        nan, 0.86768975, 0.37727881],
       [       nan, 2.00634172, 2.28991823, 1.94717079],
       [1.6028443 , 0.92250731, 1.37033591, 0.87196522]])

In [1137]:
um.get_arccosh()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:88: RuntimeWarning: invalid value encountered in arccosh


array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]])

In [1138]:
um.get_arcsin()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:91: RuntimeWarning: invalid value encountered in arcsin


array([[-0.78403167,         nan,  0.70310657,  1.19351752],
       [        nan, -0.43554539, -0.7191219 , -0.37637446],
       [-0.03204797,  0.64828901,  0.20046041,  0.69883111]])

In [1139]:
um.get_arcsinh()

array([[-0.65768929, -0.88997107,  0.60836351,  0.83075882],
       [-1.56909373, -0.41029593, -0.61852453, -0.35974151],
       [-0.03203701,  0.5721007 ,  0.19782766,  0.60561768]])

In [1140]:
um.get_arctan()

array([[-0.6148348 , -0.79145902,  0.57397473,  0.74896793],
       [-1.16019631, -0.39924618, -0.58248384, -0.35222422],
       [-0.03203153,  0.54322611,  0.19654979,  0.57166721]])

In [1141]:
um.get_arctanh()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:100: RuntimeWarning: invalid value encountered in arctanh


array([[-0.8794424 ,         nan,  0.76941751,  1.65595692],
       [        nan, -0.45000722, -0.79055665, -0.38558877],
       [-0.03205346,  0.69914286,  0.20181662,  0.76382294]])

In [1142]:
um.get_logical_not()

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [1143]:
um=UnaryMethods(arr45,copy_number=3)
um.arr2d

array([[-9, -8, -7, -6, -5],
       [-4, -3, -2, -1,  0],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [1144]:
res=um.repeat()
res

array([[[-9, -8, -7, -6, -5],
        [-4, -3, -2, -1,  0],
        [ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[-9, -8, -7, -6, -5],
        [-4, -3, -2, -1,  0],
        [ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[-9, -8, -7, -6, -5],
        [-4, -3, -2, -1,  0],
        [ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [1145]:
res.shape

(3, 4, 5)