<a href="https://colab.research.google.com/github/Lekuro/Intership_ML/blob/lesson_07_numpy/lesson_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [935]:
import numpy as np

In [936]:
arr_int=np.random.randint(-100,100, size=(4,5))
arr_int

array([[-35,  98, -43, -46,  69],
       [-41, -97,  -4, -97, -17],
       [ 10, -25, -32,  12, -85],
       [ 50,  67,  29, -31, -35]])

In [937]:
arr_n=np.random.randn(4,5)

In [938]:
arr=np.arange(-9,11)
arr

array([-9, -8, -7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,
        8,  9, 10])

# Новий розділ

In [939]:
arr45=arr.reshape(4,5)
arr45

array([[-9, -8, -7, -6, -5],
       [-4, -3, -2, -1,  0],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [940]:
arr45.shape

(4, 5)

In [941]:
arr_copy=np.copy(arr45[:3,:4])
arr_copy

array([[-9, -8, -7, -6],
       [-4, -3, -2, -1],
       [ 1,  2,  3,  4]])

In [942]:
arr_copy[2:]=0
arr_copy[:,3:]=0
arr_copy

array([[-9, -8, -7,  0],
       [-4, -3, -2,  0],
       [ 0,  0,  0,  0]])

In [943]:
arr_copy[:2,:3]

array([[-9, -8, -7],
       [-4, -3, -2]])

In [944]:
arr45

array([[-9, -8, -7, -6, -5],
       [-4, -3, -2, -1,  0],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [945]:
arr451=arr45[..., np.newaxis]
arr451

array([[[-9],
        [-8],
        [-7],
        [-6],
        [-5]],

       [[-4],
        [-3],
        [-2],
        [-1],
        [ 0]],

       [[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [946]:
arr451.shape

(4, 5, 1)

In [947]:
class UnaryMethods:
  def __init__(self,arr2d,slice_list=[],copy_number=1):
    slice_data=slice_list if slice_list else arr2d.shape
    # self.arr2d=np.copy(arr2d[:slice_data[0],:slice_data[1]])
    self.arr2d=arr2d[:slice_data[0],:slice_data[1]]
    self.copy=copy_number

  def repeat(self):
    if self.arr3d or self.arr3d.shape==self.copy:
      return self.arr3d
    self.arr3d=self.arr2d[...,np.newaxis]
    self.arr3d= np.repeat(self.arr3d,self.copy, axis=2)
    return self.arr3d

  def get_abs(self):
    return np.abs(self.arr2d)

  def get_sqrt(self):
    return np.sqrt(self.arr2d)

  def get_square(self):
    return np.square(self.arr2d)

  def get_exp(self):
    return np.exp(self.arr2d)

  def get_log(self):
    return np.log(self.arr2d)

  def get_log10(self):
    return np.log10(self.arr2d)

  def get_log2(self):
    return np.log2(self.arr2d)

  def get_log1p(self):
    return np.log1p(self.arr2d)

  def get_sign(self):
    return np.sign(self.arr2d)

  def get_ceil(self):
    return np.ceil(self.arr2d)

  def get_floor(self):
    return np.floor(self.arr2d)

  def get_rint(self):
    return np.rint(self.arr2d)

  def get_modf(self):
    return np.modf(self.arr2d)

  def get_isnan(self):
    return np.isnan(self.arr2d)

  def get_isfinite(self):
    return np.isfinite(self.arr2d)

  def get_isinf(self):
    return np.isinf(self.arr2d)

  def get_cos(self):
    return np.cos(self.arr2d)

  def get_cosh(self):
    return np.cosh(self.arr2d)

  def get_sin(self):
    return np.sin(self.arr2d)

  def get_sinh(self):
    return np.sinh(self.arr2d)

  def get_tan(self):
    return np.tan(self.arr2d)

  def get_tanh(self):
    return np.tanh(self.arr2d)

  def get_arccos(self):
    return np.arccos(self.arr2d)

  def get_arccosh(self):
    return np.arccosh(self.arr2d)

  def get_arcsin(self):
    return np.arcsin(self.arr2d)

  def get_arcsinh(self):
    return np.arcsinh(self.arr2d)

  def get_arctan(self):
    return np.arctan(self.arr2d)

  def get_arctanh(self):
    return np.arctanh(self.arr2d)

  def get_logical_not(self):
    return np.logical_not(self.arr2d)

In [948]:
um=UnaryMethods(arr_n,(3,4),2)
um.arr2d

array([[ 0.57652485,  1.90185987,  0.45282155,  0.27840136],
       [-0.88926618, -1.6935088 , -0.57542745, -1.67527692],
       [ 1.48434017, -0.50602426, -0.14433872, -1.25620973]])

In [949]:
um.repeat()

array([[[ 0.57652485,  0.57652485],
        [ 1.90185987,  1.90185987],
        [ 0.45282155,  0.45282155],
        [ 0.27840136,  0.27840136]],

       [[-0.88926618, -0.88926618],
        [-1.6935088 , -1.6935088 ],
        [-0.57542745, -0.57542745],
        [-1.67527692, -1.67527692]],

       [[ 1.48434017,  1.48434017],
        [-0.50602426, -0.50602426],
        [-0.14433872, -0.14433872],
        [-1.25620973, -1.25620973]]])

In [950]:
um.arr3d.shape

(3, 4, 2)

In [951]:
um.get_abs()

array([[0.57652485, 1.90185987, 0.45282155, 0.27840136],
       [0.88926618, 1.6935088 , 0.57542745, 1.67527692],
       [1.48434017, 0.50602426, 0.14433872, 1.25620973]])

In [952]:
um.get_square()

array([[0.3323809 , 3.61707098, 0.20504736, 0.07750732],
       [0.79079433, 2.86797204, 0.33111675, 2.80655277],
       [2.20326575, 0.25606055, 0.02083367, 1.57806287]])

In [953]:
um.get_sqrt()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: RuntimeWarning: invalid value encountered in sqrt


array([[0.75929233, 1.37907936, 0.67292017, 0.52763753],
       [       nan,        nan,        nan,        nan],
       [1.218335  ,        nan,        nan,        nan]])

In [954]:
um.get_exp()

array([[1.77984245, 6.69834093, 1.5727435 , 1.3210163 ],
       [0.41095721, 0.18387322, 0.56246439, 0.18725632],
       [4.41205326, 0.60288775, 0.8655945 , 0.28473119]])

In [955]:
um.get_log()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:26: RuntimeWarning: invalid value encountered in log


array([[-0.55073684,  0.64283229, -0.79225716, -1.27869145],
       [        nan,         nan,         nan,         nan],
       [ 0.39497035,         nan,         nan,         nan]])

In [956]:
um.get_log10()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:29: RuntimeWarning: invalid value encountered in log10


array([[-0.23918197,  0.27917852, -0.34407291, -0.55532864],
       [        nan,         nan,         nan,         nan],
       [ 0.17153344,         nan,         nan,         nan]])

In [957]:
um.get_log2()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:32: RuntimeWarning: invalid value encountered in log2


array([[-0.79454531,  0.92741095, -1.14298548, -1.84476182],
       [        nan,         nan,         nan,         nan],
       [ 0.56982176,         nan,         nan,         nan]])

In [958]:
um.get_log1p()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:35: RuntimeWarning: invalid value encountered in log1p


array([[ 0.45522296,  1.06535187,  0.37350756,  0.24561036],
       [-2.20062594,         nan, -0.85667237,         nan],
       [ 0.9100071 , -0.70526887, -0.15588068,         nan]])

In [959]:
um.get_sign()

array([[ 1.,  1.,  1.,  1.],
       [-1., -1., -1., -1.],
       [ 1., -1., -1., -1.]])

In [960]:
um.get_ceil()

array([[ 1.,  2.,  1.,  1.],
       [-0., -1., -0., -1.],
       [ 2., -0., -0., -1.]])

In [961]:
um.get_floor()

array([[ 0.,  1.,  0.,  0.],
       [-1., -2., -1., -2.],
       [ 1., -1., -1., -2.]])

In [962]:
um.get_rint()

array([[ 1.,  2.,  0.,  0.],
       [-1., -2., -1., -2.],
       [ 1., -1., -0., -1.]])

In [963]:
um.get_modf()

(array([[ 0.57652485,  0.90185987,  0.45282155,  0.27840136],
        [-0.88926618, -0.6935088 , -0.57542745, -0.67527692],
        [ 0.48434017, -0.50602426, -0.14433872, -0.25620973]]),
 array([[ 0.,  1.,  0.,  0.],
        [-0., -1., -0., -1.],
        [ 1., -0., -0., -1.]]))

In [964]:
um.get_isnan()

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [965]:
um.get_isfinite()

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [966]:
um.get_isinf()

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [967]:
um.get_cos()

array([[ 0.83836206, -0.325049  ,  0.89921624,  0.961496  ],
       [ 0.62998209, -0.12240473,  0.83895977, -0.10429061],
       [ 0.08634849,  0.87467847,  0.98960124,  0.30942339]])

In [968]:
um.get_cosh()

array([[1.17084497, 3.42381581, 1.10428755, 1.03900461],
       [1.42215028, 2.81120159, 1.17017736, 2.76376505],
       [2.31935255, 1.13078566, 1.01043493, 1.89840783]])

In [969]:
um.get_sin()

array([[ 0.5451138 ,  0.94569717,  0.43750446,  0.27481892],
       [-0.77660966, -0.99248027, -0.54419345, -0.99454687],
       [ 0.99626499, -0.48470359, -0.14383806, -0.95092438]])

In [970]:
um.get_sinh()

array([[ 0.60899748,  3.27452512,  0.46845596,  0.28201168],
       [-1.01119307, -2.62732837, -0.60771296, -2.57650874],
       [ 2.09270071, -0.52789791, -0.14484043, -1.61367664]])

In [971]:
um.get_tan()

array([[ 0.65021287, -2.90939877,  0.48653976,  0.2858243 ],
       [-1.23274879,  8.1081858 , -0.64865262,  9.53630294],
       [11.5377235 , -0.55415059, -0.14534951, -3.0732143 ]])

In [972]:
um.get_tanh()

array([[ 0.52013503,  0.9563964 ,  0.42421556,  0.27142486],
       [-0.71103109, -0.93459266, -0.51933406, -0.93224594],
       [ 0.90227797, -0.46684171, -0.14334463, -0.85001579]])

In [973]:
um.get_arccos()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:80: RuntimeWarning: invalid value encountered in arccos


array([[0.95632719,        nan, 1.10086893, 1.28866706],
       [2.66653461,        nan, 2.18392302,        nan],
       [       nan, 2.1013654 , 1.71564099,        nan]])

In [974]:
um.get_arccosh()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:83: RuntimeWarning: invalid value encountered in arccosh


array([[       nan, 1.25834628,        nan,        nan],
       [       nan,        nan,        nan,        nan],
       [0.94828342,        nan,        nan,        nan]])

In [975]:
um.get_arcsin()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:86: RuntimeWarning: invalid value encountered in arcsin


array([[ 0.61446914,         nan,  0.46992739,  0.28212927],
       [-1.09573829,         nan, -0.6131267 ,         nan],
       [        nan, -0.53056907, -0.14484466,         nan]])

In [976]:
um.get_arcsinh()

array([[ 0.54859118,  1.39886426,  0.43862134,  0.27492494],
       [-0.80086723, -1.29752458, -0.54764024, -1.28821721],
       [ 1.1860452 , -0.48659358, -0.14384218, -1.05146633]])

In [977]:
um.get_arctan()

array([[ 0.52297949,  1.08672153,  0.42519785,  0.27152567],
       [-0.72685306, -1.03739882, -0.52215546, -1.03264738],
       [ 0.97794027, -0.46845539, -0.1433487 , -0.89847137]])

In [978]:
um.get_arctanh()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:95: RuntimeWarning: invalid value encountered in arctanh


array([[ 0.6572417 ,         nan,  0.48824393,  0.28594828],
       [-1.41840721,         nan, -0.6555995 ,         nan],
       [        nan, -0.55737105, -0.14535381,         nan]])

In [979]:
um.get_logical_not()

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [987]:
um=UnaryMethods(arr45,copy_number=3)
um.arr2d

array([[-9, -8, -7, -6, -5],
       [-4, -3, -2, -1,  0],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [988]:
res=um.repeat()
res

array([[[-9, -9, -9],
        [-8, -8, -8],
        [-7, -7, -7],
        [-6, -6, -6],
        [-5, -5, -5]],

       [[-4, -4, -4],
        [-3, -3, -3],
        [-2, -2, -2],
        [-1, -1, -1],
        [ 0,  0,  0]],

       [[ 1,  1,  1],
        [ 2,  2,  2],
        [ 3,  3,  3],
        [ 4,  4,  4],
        [ 5,  5,  5]],

       [[ 6,  6,  6],
        [ 7,  7,  7],
        [ 8,  8,  8],
        [ 9,  9,  9],
        [10, 10, 10]]])

In [989]:
res.shape

(4, 5, 3)